algoritmo "semnome"
// Função :
// Autor :
// Data : 12/08/2019
// Seção de Declarações 
var
cont,s,n,maio,meno:inteiro
inicio
meno<-9999999
cont <- 1
s<-0
enquanto (cont<=10)faca
escreval("digite o ",cont," valor")
leia(n)
se (n>maio)entao
maio<-n
FimSe

s<-s+n
cont<-cont+1
fimenquanto


escreval ("A soma de todos os valores foi ",s," O maior número é ", maio)
escreval ("O menor número é ", meno)
fimalgoritmo
